### PR TITLE
Fixes #157 Do not allow to create .zim inside of source HTML dir

### LINKED ISSUE #157: zimwriterfs error (Assertion failed at .... libzim_release/src/writer/creator.cpp:297)
Using zim-tools_linux-x86_64-2.0.0-1 binaries on ubuntu 20.04

zimdump'ed wikispecies_en_all_maxi_2020-06.zim

`zimdump dump --dir=./wikispecies_en_all_maxi_2020-06 wikispecies_en_all_maxi_2020-06.zim`

Then immediately tried to remake a zim file

`zimwriterfs --welcome=A/Main_Page --favicon=-/favicon.png --language=eng --title=mytest --description=ThisIsATest --creator=self --publisher=self --inflateHtml --verbose . my_project.zim` 

If runs for a while and ends with this

> T:202; A:1166000; RA:1; CA:58; UA:1165941; FA:1165972; IA:0; C:3094; CC:0; UC:3094; WC:0
> T:202; A:1166850; RA:1; CA:59; UA:1166790; FA:1166821; IA:0; C:3096; CC:0; UC:3096; WC:0
> T:203; Waiting for workers
> T:203; ResolveRedirectIndexes
> Resolve redirect
> T:203; Set article indexes
> set index
> T:203; Resolve mimetype
> T:206; create title index
> T:207; 1166852 title index created
> T:207; 3098 clusters created
> T:207; write zimfile :
> T:208;  write mimetype list
> 
> Assertion failed at ../../SOURCE/libzim_release/src/writer/creator.cpp:297
>  lseek(out_fd, 0, SEEK_CUR)[470937] < CLUSTER_BASE_OFFSET[1024]
> [0x43aba4]
> [0x433591]
> [0x4371d0]
> [0x41ffc8]
> [0x40a84c]
> [0x94cac6]
> [0x94d0b5]
> [0x40e769]
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  
> Assertion failed at ../../SOURCE/libzim_release/src/writer/creator.cpp:297
>  lseek(out_fd, 0, SEEK_CUR)[470937] < CLUSTER_BASE_OFFSET[1024]
> Aborted

### PR DESCRIPTION
**Pull request by asashnov**
Fixes #157: Prevent creation of .zim under HTML source directory.

### CODE REVIEW

**Comment by asashnov** [comment]
Dispite on checking zimdir size, CodeFactor is still unhappy:

```
[Severity: Minor] Use of strtrns (CWE-120, CWE-785) lines of code = 1
[Read Up]

This function does not protect against buffer overflows, and some implementations can overflow internally (CWE-120/CWE-785!).

Ensure that the destination buffer is at least of size MAXPATHLEN, andto protect against implementation problems, the input argument should also be checked to ensure it is no larger than MAXPATHLEN.

Found in src\zimwriterfs\zimwriterfs.cpp:363
363

  if (realpath(zimdir.c_str(), buf) != buf)
```

Probably it's not smart enough to 'see' this check.

**Comment by kelson42** [comment]
I made a rebased on git `master`.

**Comment by kelson42** [comment]
@asashnov Please secure the CI pass (it does not anymore).

**Comment by asashnov** [comment]
> @asashnov Please secure the CI pass (it does not anymore).

Done

**Comment by kelson42** [comment]
@mgautierfr Can we review/merge this please?

File: src/zimwriterfs/zimwriterfs.cpp [hunk 1]
```diff
@@ -346,6 +349,26 @@ void create_zim()
 {
   ZimCreatorFS zimCreator(directoryPath, welcome, isVerbose(), uniqueNamespace, zstdFlag);
 
+  if (zimPath.size() >= (MAXPATHLEN-1))
+    throw std::invalid_argument("Target .zim file path is too long");
+
+  // dirname() can modify the 'buf', no c_str() here.
+  char buf[MAXPATHLEN];
+  strncpy(buf, zimPath.c_str(), sizeof(buf));
```
Comment (mgautierfr) [inline src/zimwriterfs/zimwriterfs.cpp]: We are reading after zimPath here. (sizeof(buf) > zimPath.size()).
This is not a problem as c_str() ensure there is a `\0` at the end of the string, but I dislike it anyway :)

We don't need to initialize `buf` with zimPath. We can initialize `zimdir` with `zimPath.c_str()`.

File: src/zimwriterfs/zimwriterfs.cpp [hunk 2]
```diff
@@ -346,6 +349,26 @@ void create_zim()
...
+  std::string zimdir = dirname(buf);
+
+  if (zimdir.size() >= MAXPATHLEN)
+    throw std::invalid_argument("Target .zim directory path is too long");
+
+  if (realpath(zimdir.c_str(), buf) != buf)
```
Comment (mgautierfr) [inline src/zimwriterfs/zimwriterfs.cpp:364]: I dislike `if` test without `{}`. Especially if there are several lines after it.

I prefer to always have the coding style :

```
if (foo) {
    bar;
}
```

Even if there is only one instruction in the `if`.

**Review by mgautierfr — CHANGES_REQUESTED** [review]

**Comment by mgautierfr** [comment]
And this need to be rebased on master. The bug with zimsplit has already been fixed there.

File: src/zimwriterfs/zimwriterfs.cpp (hunk 1 above)
Comment (asashnov) [reply src/zimwriterfs/zimwriterfs.cpp:357]: Not exactly. zimdir is initialized with _the result_ of dirname(), but we cannot pass c_str() to dirname() because it takes `char *` (not `const char *`).

**Comment by kelson42** [comment]
Rebased
